"""empty message

Revision ID: 1b897cb49ec1
Revises: f5045ada7fd0
Create Date: 2022-12-11 19:10:57.829824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b897cb49ec1'
down_revision = 'f5045ada7fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
